#!/bin/sh
module="pvdspb_adc"
device="pvdspb_adc"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi


# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

major=`grep ${module} /proc/devices | awk '{print \$1}'`

# Create entry point
rm -f /dev/${device}1
mknod /dev/${device}1 c $major 0

chgrp $group /dev/${device}1
chmod $mode  /dev/${device}1






